baresip: fix build failure on 32bit x86 targets
re and baresip builds for 32bit x86 targets are currently failing:

build-i386/sip/auth.o: In function `sip_auth_encode':
/build/lede-snapshots/i386_pentium/build/sdk/build_dir/target-i386_pentium_musl/re-0.5.6/src/sip/auth.c:279: undefined reference to `__stack_chk_fail_local'

The undefined references occur because there is no linking done to ssp.
Fix this by setting LD to TARGET_CC, so ld is not called directly. This
also means one patch is not needed anymore.

Do the same for rem and restund as they basically all share the same
build system.

Compile-tested for x86, x86_64 and mips.

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>