asterisk-11x: Update 010-asterisk-configure-undef-res-ninit.patch
Lately configure is recreated from configure.ac. The current patch changes configure. So we patch it, then it gets recreated and our change is gone. So patch configure.ac instead. Without this change the build fails due to an undefined reference to res_nsearch.

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>