rtpproxy: bump to version 2025-11-04
Bump rtpproxy to version 2025-11-04. Each downstream patch got merged
and this fix the current compilation error with recvfromto.

rtpp_socket.c: In function 'rtpp_socket_rtp_recv':
rtpp_socket.c:262:31: error: passing argument 5 of 'recvfromto' from incompatible pointer type [-Wincompatible-pointer-types]
  262 |       sstosa(&packet->raddr), &packet->rlen, sstosa(&packet->_laddr), &llen,
      |                               ^~~~~~~~~~~~~
      |                               |
      |                               socklen_t * {aka unsigned int *}
In file included from rtpp_socket.c:45:
rtpp_network.h:56:3: note: expected 'size_t *' {aka 'long unsigned int *'} but argument is of type 'socklen_t *' {aka 'unsigned int *'}
   56 |   size_t *, struct sockaddr *, size_t *, struct timeval *);
      |   ^~~~~~~~

2 new trivial pending patch (proposed upstream) are now required to
permit correct compilation.

This bump from 2.x to 3.x but checking the changlog no breaking change
should be triggered by this version jump.

Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>