net/asterisk-13.x: prevent libsrtp2 detection
Asterisk 13 looks for libsrtp2. Unfortunately it also looks for a header
which libsrtp2 does not make public:

res_srtp.c:44:33: fatal error: srtp2/crypto_types.h: No such file or directory
compilation terminated.

This causes the asterisk build to fail. Fix this by disabling libsrtp2
detection in Asterisk 13.

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>