re: fix build errors on mipsel targets
On most mipsel targets re fails to build because the re Makefile adds
"-march=mips32" to CFLAGS:

Assembler messages:
Error: -mips32r2 conflicts with the other architecture options, which imply -mips32
src/sip/addr.c:1:0: error: '-mips32r2' conflicts with the other architecture options, which specify a mips32 processor
 /**
 ^
Makefile:92: recipe for target 'build-mipsel/sip/addr.o' failed

Fix this by preventing re from adding to OpenWrt CFLAGS.

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>