baresip: add symbol to prevent FFmpeg dependency by default
Currently baresip often fails to build because the FFmpeg compile was
not successful:

  CC [M]  build-mipsel/modules/avcodec/avcodec.o
modules/avcodec/avcodec.c:9:32: fatal error: libavcodec/avcodec.h: No such file or directory
compilation terminated.

Address this by adding a configuration symbol that prevents the
FFmpeg-depending modules from being selected by default, except on i386
and x86_64.

It is better having baresip packages without these video modules than
not having baresip packages at all.

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>