gsmlib: disable NLS
It's not wanted, so add "--disable-nls" to override user selecting
CONFIG_BUILD_NLS.

This also updates 01-update-autotools.patch to make these disappear:

ERROR: Use of AM_GNU_GETTEXT without [external] argument is no longer supported.

Makefile.am:21: warning: 'intl' should not be in SUBDIRS when AM_GNU_GETTEXT([external]) is used

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>
(cherry picked from commit b86cf0cdc66d056be13ae49563d9bf5aadf28e78)