yate: Prevent build failures due to inclusion of fortify-source headers
yate cannot be compiled against fortify-source headers at this moment:

  In file included from /home/sk/tmp/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/include/fortify/unistd.h:23:0,
                   from ../yateclass.h:32,
                   from ../yatengine.h:29,
                   from ../yatephone.h:29,
                   from server/ysnmpagent.cpp:22:
  /home/sk/tmp/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/include/fortify/fortify-headers.h:20:42: error: type of 'TelEngine::strcat' is unknown

To work around this remove CPPFLAGS from CFLAGS.

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>